### ISSUE TITLE
Error Loading Background - Cannot Read Properties of Null

### ISSUE THREAD

**Issue by BerkSmash1984** [Andoramb/MMM-CivitAI#1]
Attempted to use this module, but I am seeing this on my MM. Any ideas?
![image](https://github.com/Andoramb/MMM-CivitAI/assets/104693081/0ff3d84d-5c9c-4f20-86a3-77deb6d0954f)

Note, I am using MMM-Pages on my mirror.

Dev console shows this, but doesn't look too informative:
![image](https://github.com/Andoramb/MMM-CivitAI/assets/104693081/a17bae2a-4733-490b-8803-da3da13c1111)

**Comment by Andoramb** [comment]
Hi,

I can investigate this after the Christmas period, but until that, here's a basic config that works for me:
```
{
                          module: "MMM-CivitAI",
                          position: "fullscreen_below",
                          config: {
                                  addBackgroundFade: ["top", "bottom"],
                                  limit: 10,
                                  showPrompt: true,
                                  showUsername: true,
                                  nsfw: "None",
                                  sort: "Most Reactions",
                                  period: "Day"
                          }
                    },
```

**Comment by Andoramb** [comment]
On a second thought...

I've made some updates to the code, it should be fine now.
You can try testing it with the config above. 

Let me know if it works now. 👍

**Comment by BerkSmash1984** [comment]
Awesome! I’ll test as soon as I get home. Appreciate it!


Jordan

**Comment by BerkSmash1984** [comment]
@Andoramb It is working great now, thanks! Question for you, can you add to your configuration to support a horizontal view? I currently have my MM display running from a monitor that is displayed horizontally. and thus the module cuts off a good amount of the picture:

![image](https://github.com/Andoramb/MMM-CivitAI/assets/104693081/689752d8-e14f-483b-b33a-f514077fe701)

Thanks for your work on this module!

**Comment by Andoramb** [comment]
Hi,
I just pushed an update to the module, cleared some stuff and added a couple features:

- check out `resizeMode: "height"`, it should fix the image to the height of the screen
- minor, but there's a nice blur filter as well.

Let me know how it worked out!

**Comment by BerkSmash1984** [comment]
Cool! I'll check it out today! For the next update, any chance you can define a width and height so we can use the module in one of the traditional positions instead of full screen? Switch to using my MM on a horizontal 10 inch display and would like to use the module on a page with other modules showing. Thanks!

**Comment by Andoramb** [comment]
Right.
But let's close this, as the main issue was solved :)

**Comment by BerkSmash1984** [comment]
100% Thanks for updating the module to resolve this issue!

Respectfully,

Jordan Berkebile
